#!/bin/bash
#
# Entrypoint for php-actions/phpstan
#

set -e

Get_command()
{
	echo -n "phpstan --no-interaction --no-progress ${action_command}"
	for env in action_configuration action_level \
			   action_paths_file action_autoload_file action_error_format \
			   action_generate_baseline action_memory_limit
	do
		option="${!env}"
		option_name="${env#action_}"
		if [ -z "${option}" ]; then
			continue
		fi
		echo -n " --${option_name//_/-}='${option}'"
	done
	echo -n " ${action_args} ${action_path}"
}

command_string="$(Get_command)"

echo "Command: ${command_string}"
eval "${command_string}"
